sudo: required

dist: trusty

services:
  - docker

before_script:
  - |
    mkdir ubuntu-16.04
    cat <<EOF > ubuntu-16.04/Dockerfile
    FROM ubuntu:16.04
    RUN apt-get update
    RUN apt-get install -y git build-essential cmake libmbedtls-dev \
        libssl-dev python3 libboost-python-dev libpython3-dev wget \
        python3-sphinx $CC $CXX
    RUN git clone https://github.com/AVSystem/Anjay.git
    RUN sed -i -e "s/-Wdate-time/ /g" \
        /usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/Makefile \
        /usr/lib/python3.5/plat-x86_64-linux-gnu/_sysconfigdata_m.py
    CMD cd Anjay && ./devconfig && make -j && make check
  - |
    mkdir centos7
    cat <<EOF > centos7/Dockerfile
    FROM centos:7
    # required for mbedtls-devel and python3.5
    RUN yum install -y https://centos7.iuscommunity.org/ius-release.rpm
    RUN yum install -y which git make cmake3 boost-python-devel mbedtls-devel openssl openssl-devel wget python-sphinx python-sphinx_rtd_theme valgrind valgrind-devel gcc gcc-c++
    # required to compile boost::python
    RUN yum install -y boost-jam python-tools
    RUN yum install -y python35u python35u-devel
    RUN yum install -y http://pubrepo.maxiv.lu.se/rpm/el7/x86_64/boost-python3-1.53.0-25.el7.x86_64.rpm
    RUN rpm -ivh --nodeps http://pubrepo.maxiv.lu.se/rpm/el7/x86_64/boost-python3-devel-1.53.0-25.el7.x86_64.rpm
    RUN ln -s /usr/bin/cmake3 /usr/bin/cmake
    RUN ln -s /usr/bin/python3.5 /usr/bin/python3
    RUN git clone https://github.com/AVSystem/Anjay.git
    CMD cd Anjay && ./devconfig -DPython_ADDITIONAL_VERSIONS=3.5 && make -j && make check

script:
  - docker build -t "$DOCKER_IMAGE" "$DOCKER_IMAGE"
  - docker run -e CC=$CC -e CXX=$CXX "$DOCKER_IMAGE"

env:
  - CC=gcc-4.7
    CXX=g++-4.7
    DOCKER_IMAGE=ubuntu-16.04

  - CC=gcc-4.8
    CXX=g++-4.8
    DOCKER_IMAGE=ubuntu-16.04

  - CC=gcc-4.9
    CXX=g++-4.9
    DOCKER_IMAGE=ubuntu-16.04

  - CC=gcc-5
    CXX=g++-5
    DOCKER_IMAGE=ubuntu-16.04

  - CC=clang-3.5
    CXX=clang++-3.5
    DOCKER_IMAGE=ubuntu-16.04

  - CC=clang-3.6
    CXX=clang++-3.6
    DOCKER_IMAGE=ubuntu-16.04

  - CC=clang-3.7
    CXX=clang++-3.7
    DOCKER_IMAGE=ubuntu-16.04

  - CC=clang-3.8
    CXX=clang++-3.8
    DOCKER_IMAGE=ubuntu-16.04

  - DOCKER_IMAGE=centos7
